### ISSUE TITLE
Can we extact map information from pycmo (height info, water, etc.) 

### ISSUE THREAD

**Issue by johnrachwan123** [duyminh1998/pycmo#4]

**Comment by duyminh1998** [comment]
There are several ways to accomplish this. First, what specific variables do you want to extract? If you want to extract weather information (e.g. temperature, pressure, sea state, etc.), then that information is embedded in the XML file that is transformed at every time step by the **get_obs()** function into a **Features** object. The **Features** object parses the XML file and extracts the most relevant parameters for training agents. As a result, you will need to edit the **Features** object so that it also extracts and holds weather data. 

There is a separate type of environmental data that can be extracted (e.g. elevation, altitude, layer, etc.). Referring to the game’s [documentation](https://commandlua.github.io/#World_GetLocation), we can use the **World_GetLocation()** function to return a table of environmental details at that location. Now, the tricky thing is exporting this information at every time step. I can think of two methods. 

**A. Use the game’s internal key store** 
1. Save the information in the game’s key store using **ScenEdit_SetKeyValue(key, value)**. For example, you can do **ScenEdit_SetKeyValue(“Elevation”, elevation)**, where elevation can presumably hold elevation data from an earlier function call. 
2. Then, these key-value pairs are exported alongside the XML file that gets outputted at every time step, so just write extra code in the Features object to also parse these key-value pairs. 

**B. Write the information to an external file using Lua’s io library.** This is the more obvious, but less elegant way. You can just write the map data out to an external file using Lua’s io library and read it from Python.

**Comment by johnrachwan123** [comment]
Thank you for the detailed reply!
