### ISSUE TITLE
Is PyCMO compatible with Command Modern Operations or only Command Professional Edition ? 

### ISSUE THREAD

**Issue by johnrachwan123** [duyminh1998/pycmo#5]
I was wondering whether the library strictly requires a professional edition or it can also be used with commercial version on Steam. If yes, do you have a setup guide to interact with CMO ? 

Thank you in advance for your help!

**Comment by duyminh1998** [comment]
John,

In order to output data (observations) to your local system, a Profession Edition of Command is required. I will do further experimentation with the commercial Steam version but it is my understanding that you cannot output files. I also do not think that you can send commands to the game because pycmo sends it through an open TCP/IP socket and you can only open that with a Professional version I think.
